--Q10--
(SELECT NAMEFIRST|| ' ' ||NAMELAST AS full_name,
			MAX(HR) AS MOST_HR
		FROM BATTING
		INNER JOIN PEOPLE USING (PLAYERID)
		WHERE HR > 0
			AND (FINALGAME::DATE - DEBUT::DATE) >= 3650
			AND YEARID = 2016
		GROUP BY PLAYERID,
			NAMEFIRST|| ' ' ||NAMELAST) INTERSECT
	(SELECT NAMEFIRST|| ' ' ||NAMELAST,
			MAX(HR) AS MOST_HR
		FROM BATTING
		INNER JOIN PEOPLE USING (PLAYERID)
		WHERE HR > 0
			AND (FINALGAME::DATE - DEBUT::DATE) >= 3650
		GROUP BY PLAYERID,
			NAMEFIRST|| ' ' ||NAMELAST)
ORDER BY MOST_HR DESC;




